### ISSUE TITLE
Getting 402 payment required as of Aug 12.

### ISSUE THREAD

**Issue by sebsx** [lucasasselli/garmin-podcasts#15] opened 2021-08-12 09:20 UTC
Installed today and tried to sync a few podcasts. Got HTTP 402 for all of them and eventually completel;y drained my Fenix 6 battery. Let me know if you need more info or want me to try again.

**Comment by lucasasselli** [comment] 2021-08-13 16:36
Do you get 402 or -402? -402 is a Garmin internal error for "NETWORK_RESPONSE_TOO_LARGE". When do you get this error? Can you provide some details for me to recreate the issue?

**Comment by lucasasselli** [comment] 2021-08-17 17:20
I just published an update (3.1.5) that should drastically mitigate error -402. Please let me know if it works for you.

**Comment by mathsaey** [comment] 2021-08-28 00:18
I consistently get a error -402 when trying to sync the "critical role" podcast (not the one by nerdist industries, the one from critical role). Not sure if this is the same issue as OP is facing but figured it's related enough to chime in.

Let me know if you need any info from my end to reproduce.

**Comment by lucasasselli** [comment] 2021-08-28 11:21
Hi Mathijs,

I think it's likely the same issue. What version of Podcast are you using?
On what device you observe the issue?

**Comment by lucasasselli** [comment] 2021-08-29 22:19
You can check the version of the app if you select it in Connect IQ, under "Additional information". The latest is 3.1.7. 

When do you see the error? During sync or episode selection? Are you suing gPodder?

**Comment by mathsaey** [comment] 2021-08-29 23:08
> You can check the version of the app if you select it in Connect IQ, under "Additional information". The latest is 3.1.7.

Turns out the reason I couldn't see the version is because the app is no longer marked as being compatible with the 945LTE. The app was therefore in some limbo state where it was installed on my device but no longer supported. Of course, I only figured this out after trying to reinstall the app.

Could you mark the app as being compatible with the 945LTE? Would you prefer it if I opened a new issue for this?

> When do you see the error? During sync or episode selection? Are you suing gPodder?

The error occurred during episode selection, more specifically when selecting a show: when the app was fetching the list of episodes it consistently returned the -402 error. I was not using gPodder.

**Comment by lucasasselli** [comment] 2021-08-30 20:27
Just published an update to include the 945 LTE (3.1.8). Please let me know if it works!

**Comment by mathsaey** [comment] 2021-08-30 21:40
Can confirm both installation on 945LTE and syncing work fine for me in 3.1.8. Thanks for responding so fast and helping me out!

**Closed** 2021-09-08 07:54 UTC
Labels: bug
